/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalsystem;

/**
 *
 * @author tonio
 */
import java.util.ArrayList;
public class HospitalSystemPatientView extends javax.swing.JFrame {
    static HospitalSystemController c = new HospitalSystemController(new HospitalSystemModel(),new HospitalSystemLogInView(),new HospitalSystemPatientView());
    private ArrayList<String> Patients;
    public HospitalSystemPatientView(ArrayList<String> Patients) {
        //If instance is created with array as an argument, object initializes variables and updates Drop Down List with array info
        initComponents();
        this.Patients = Patients;
        this.updateDropDown(Patients);
        
        
    }
    public HospitalSystemPatientView(){
        //If instance is created with not array as an argument, object does not do anything
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PatientOptions = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PatientName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PatientNumber = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PatientAddress = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PatientCondition = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(105, 94, 147));
        jPanel1.setLayout(null);

        PatientOptions.setBackground(new java.awt.Color(239, 220, 249));
        PatientOptions.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        PatientOptions.setBorder(null);
        PatientOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(PatientOptions);
        PatientOptions.setBounds(90, 30, 220, 30);
        PatientOptions.getAccessibleContext().setAccessibleName("");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Patients Records");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 6, 220, 20);

        jPanel2.setBackground(new java.awt.Color(190, 175, 194));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(239, 220, 249));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name:");

        PatientName.setEditable(false);
        PatientName.setBackground(new java.awt.Color(239, 220, 249));
        PatientName.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        PatientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientName, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientName, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(40, 20, 230, 40);

        jPanel5.setBackground(new java.awt.Color(239, 220, 249));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phone Number:");

        PatientNumber.setEditable(false);
        PatientNumber.setBackground(new java.awt.Color(239, 220, 249));
        PatientNumber.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        PatientNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientNumber)
                .addContainerGap())
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(40, 70, 230, 40);

        jPanel6.setBackground(new java.awt.Color(239, 220, 249));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Address:");

        PatientAddress.setEditable(false);
        PatientAddress.setBackground(new java.awt.Color(239, 220, 249));
        PatientAddress.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        PatientAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(40, 120, 230, 40);

        jPanel7.setBackground(new java.awt.Color(239, 220, 249));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Condition:");

        PatientCondition.setEditable(false);
        PatientCondition.setBackground(new java.awt.Color(239, 220, 249));
        PatientCondition.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        PatientCondition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientCondition, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientCondition, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(40, 170, 230, 40);

        addButton.setBackground(new java.awt.Color(105, 94, 147));
        addButton.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton);
        addButton.setBounds(290, 20, 100, 40);

        removeButton.setBackground(new java.awt.Color(105, 94, 147));
        removeButton.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        removeButton.setText("Remove");
        removeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(removeButton);
        removeButton.setBounds(290, 70, 100, 40);

        editButton.setBackground(new java.awt.Color(105, 94, 147));
        editButton.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        editButton.setText("Edit Mode");
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel2.add(editButton);
        editButton.setBounds(290, 120, 100, 40);

        updateButton.setBackground(new java.awt.Color(105, 94, 147));
        updateButton.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        updateButton.setMargin(new java.awt.Insets(2, 15, 3, 15));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateButton);
        updateButton.setBounds(290, 170, 100, 40);

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Patient Options");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(290, 0, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientOptionsActionPerformed
        // Whenever an action is performed on the Drop Down Menu (e.g clicked), Patient info is displayed
        Patient patient = c.getPatient(PatientOptions.getSelectedItem().toString());
        this.PatientName.setText(patient.getName());
        this.PatientNumber.setText(patient.getPhoneNumber());
        this.PatientAddress.setText(patient.getAddress());
        this.PatientCondition.setText(patient.getCondition());
        this.PatientName.setEditable(false);
    }//GEN-LAST:event_PatientOptionsActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //addButton adds a new Patient to the Patients array through the Controller function & adds the Patients name to the drop down list
        c.addNewPatient(this.PatientName.getText(), this.PatientNumber.getText(), this.PatientAddress.getText(), this.PatientCondition.getText());
        this.addToDropDown(this.PatientName.getText());
        
        //Sets all Text Boxes to be empty
        this.PatientName.setText("");
        this.PatientNumber.setText("");
        this.PatientAddress.setText("");
        this.PatientCondition.setText("");
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // removeButton deletes a Patient from the Patient array using the Controller & and removes it from the drop down list via index
        c.deletePatient(this.PatientOptions.getSelectedItem().toString());
        this.removeFromDropDown(this.PatientOptions.getSelectedIndex());
    }//GEN-LAST:event_removeButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // Sets the Text Boxes to be editable 
        this.PatientName.setEditable(true);
        this.PatientNumber.setEditable(true);
        this.PatientAddress.setEditable(true);
        this.PatientCondition.setEditable(true);
        //Sets the Text Boxes to be empty
        this.PatientName.setText("");
        this.PatientNumber.setText("");
        this.PatientAddress.setText("");
        this.PatientCondition.setText("");
    }//GEN-LAST:event_editButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // updateButton uses user Input on a Patients Info to update that Patient's Information
        c.updatePatient(this.PatientName.getText(), this.PatientNumber.getText(), this.PatientAddress.getText(), this.PatientCondition.getText());
        //Sets all Text Boxes to be uneditable
        this.PatientName.setEditable(false);
        this.PatientNumber.setEditable(false);
        this.PatientAddress.setEditable(false);
        this.PatientCondition.setEditable(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void PatientStartUp(ArrayList<String> PatientList) {
        //Displays Patient view window
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalSystemPatientView(PatientList).setVisible(true);
                
                
            }
        });
    }
    private void addToDropDown(String name){
        //Adds Patient to the Drop Down list
        this.PatientOptions.addItem(name);
        this.PatientOptions.setSelectedItem(name);
    }
    private void removeFromDropDown(int index){
        //removes Patient from the Drop Down list
        this.PatientOptions.removeItemAt(index);
    }
    private void updateDropDown(ArrayList<String> Patients){
        //updates Drop Down List with Patients in array
        for(String p:Patients){
        PatientOptions.addItem(p);
        }
        this.PatientOptions.setSelectedIndex(1);
    }
                                   
                                 
                                
                                            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PatientAddress;
    private javax.swing.JTextField PatientCondition;
    private javax.swing.JTextField PatientName;
    private javax.swing.JTextField PatientNumber;
    private javax.swing.JComboBox<String> PatientOptions;
    private javax.swing.JButton addButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
